package com.shop.entity;
// Generated Oct 12, 2017 10:46:56 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CreditCard generated by hbm2java
 */
@Entity
@Table(name="credit_card"
    ,catalog="shop"
)
public class CreditCard  implements java.io.Serializable {


     private Integer id;
     private String code;
     private String pin;
     private String balance;
     private int status;

    public CreditCard() {
    }

    public CreditCard(String code, String pin, String balance, int status) {
       this.code = code;
       this.pin = pin;
       this.balance = balance;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="code", nullable=false, length=20)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="pin", nullable=false, length=20)
    public String getPin() {
        return this.pin;
    }
    
    public void setPin(String pin) {
        this.pin = pin;
    }

    
    @Column(name="balance", nullable=false, length=10)
    public String getBalance() {
        return this.balance;
    }
    
    public void setBalance(String balance) {
        this.balance = balance;
    }

    
    @Column(name="status", nullable=false)
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }




}


